
const $=s=>document.querySelector(s);let posts=[];try{posts=JSON.parse(localStorage.getItem('rwmSocialDrafts')||'[]');if(!Array.isArray(posts))posts=[]}catch{}let photoData={};let month=new Date();month.setDate(1);const names={overview:'Overview',compose:'Create a post',calendar:'Content calendar',jobs:'RWM OPS jobs',accounts:'Social accounts',analytics:'Analytics'};
function go(p){document.querySelectorAll('.section').forEach(e=>e.classList.toggle('active',e.id===p));document.querySelectorAll('nav button').forEach(e=>e.classList.toggle('active',e.dataset.page===p));$('#title').textContent=names[p];if(p==='calendar')renderCalendar()}
document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>go(b.dataset.page));document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));$('#newPost').onclick=()=>go('compose');function toast(t){$('#toast').textContent=t;$('#toast').style.display='block';setTimeout(()=>$('#toast').style.display='none',3500)}
function render(){ $('#draftCount').textContent=posts.filter(p=>(p.status||'draft')==='draft').length;$('#plannedCount').textContent=posts.filter(p=>p.at).length;$('#queue').replaceChildren();if(!posts.length){const p=document.createElement('p');p.className='empty';p.textContent='Your first post starts here. Create a draft to fill your queue.';$('#queue').append(p)}posts.forEach(p=>{const d=document.createElement('div');d.className='post';const t=document.createElement('strong');t.textContent=p.title;const meta=document.createElement('p');meta.textContent=p.platform+' · '+(p.at?new Date(p.at).toLocaleString():'Draft');const c=document.createElement('p');c.textContent=p.caption;const b=document.createElement('button');b.className='btn secondary';b.textContent='Delete draft';b.onclick=()=>{posts=posts.filter(x=>x.id!==p.id);localStorage.setItem('rwmSocialDrafts',JSON.stringify(posts));render()};meta.textContent=(p.business==='solar'?'RWM Solar':'RWM Landscaping')+' · '+(p.status==='to_write'?'To write':'Draft')+' · '+meta.textContent;const edit=document.createElement('button');edit.className='btn secondary';edit.textContent='Edit / write post';edit.onclick=()=>editPost(p);d.append(t,meta,c,edit,b);$('#queue').append(d)})}
['postTitle','caption'].forEach(id=>$('#'+id).oninput=()=>{$('#previewTitle').textContent=$('#postTitle').value||'Your next transformation';$('#previewCaption').textContent=$('#caption').value||'Your caption will appear here.'});['before','after'].forEach(id=>$('#'+id).onchange=()=>{const f=$('#'+id).files[0];if(!f)return;if(f.size>3*1024*1024){toast('Please use a photo under 3 MB for this first version.');$('#'+id).value='';return}const r=new FileReader();r.onload=()=>{photoData[id]=r.result;$('#'+id+'Preview').src=r.result;$('#'+id+'Preview').hidden=false};r.readAsDataURL(f)});
$('#suggest').onclick=()=>{$('#caption').value=`Another ${$('#service').value.toLowerCase()} project complete. Take a look at the before and after!\n\n${$('#postTitle').value||'A fresh transformation, with attention to every detail.'}\n\nReady to give your property some attention? Get in touch to discuss your next project.\n\n#RWMGroup #BeforeAndAfter`;$('#caption').dispatchEvent(new Event('input'))};$('#postForm').onsubmit=e=>{e.preventDefault();const p={id:crypto.randomUUID(),title:$('#postTitle').value,caption:$('#caption').value,business:$('#business').value,status:'draft',platform:$('#platform').value,at:$('#plannedAt').value,photos:{...photoData},consent:true};const next=[p,...posts];try{const pos=editingId?posts.findIndex(x=>x.id===editingId):-1;if(pos>=0){p.id=editingId;next.splice(0,next.length,...posts.map(x=>x.id===editingId?p:x))}localStorage.setItem('rwmSocialDrafts',JSON.stringify(next));posts=next;editingId=null;render();toast('Draft saved on this browser.');go('overview')}catch{toast('Browser storage is full. Try smaller photos or delete older drafts.')}};
function renderCalendar(){$('#monthLabel').textContent=month.toLocaleDateString(undefined,{month:'long',year:'numeric'});$('#month').replaceChildren();['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].forEach(x=>{const b=document.createElement('b');b.textContent=x;$('#month').append(b)});for(let i=0;i<month.getDay();i++)$('#month').append(document.createElement('div'));const count=new Date(month.getFullYear(),month.getMonth()+1,0).getDate();for(let day=1;day<=count;day++){const d=document.createElement('div');d.className='day';const b=document.createElement('b');b.textContent=day;d.append(b);posts.filter(p=>{const a=new Date(p.at);return p.at&&a.getFullYear()===month.getFullYear()&&a.getMonth()===month.getMonth()&&a.getDate()===day}).forEach(p=>{const s=document.createElement('span');s.textContent=p.title;d.append(s)});$('#month').append(d)}}$('#prev').onclick=()=>{month.setMonth(month.getMonth()-1);renderCalendar()};$('#next').onclick=()=>{month.setMonth(month.getMonth()+1);renderCalendar()};['Facebook','Instagram','LinkedIn','TikTok','YouTube','Google Business Profile','X','Pinterest'].forEach(n=>{const d=document.createElement('div');d.className='post';const t=document.createElement('strong');t.textContent=n;const p=document.createElement('p');p.textContent='Not connected · account linking not enabled yet';d.append(t,p);$('#accountList').append(d)});render();

let editingId=null;
function editPost(p){editingId=p.id;$('#postTitle').value=p.title;$('#caption').value=p.caption||'';$('#business').value=p.business||'landscaping';$('#service').value=p.business==='solar'?'Solar':'Landscaping';$('#platform').value=p.platform||'Facebook + Instagram';$('#plannedAt').value=p.at||'';photoData={...p.photos};['before','after'].forEach(k=>{const e=$('#'+k+'Preview');e.hidden=!photoData[k];if(photoData[k])e.src=photoData[k]});$('#permission').checked=!!p.consent;$('#caption').dispatchEvent(new Event('input'));go('compose')}
$('#newPost').onclick=()=>{editingId=null;$('#postForm').reset();photoData={};['before','after'].forEach(k=>$('#'+k+'Preview').hidden=true);$('#caption').dispatchEvent(new Event('input'));go('compose')};
$('#business').onchange=()=>{$('#service').value=$('#business').value==='solar'?'Solar':'Landscaping'};
$('#ideaForm').onsubmit=e=>{e.preventDefault();const n=Number($('#ideaCount').value);if(!Number.isInteger(n)||n<1||n>20)return;const next=[...posts];for(let i=0;i<n;i++)next.push({id:crypto.randomUUID(),business:$('#ideaBusiness').value,title:($('#ideaBusiness').value==='solar'?'Solar':'Landscaping')+' post to write',caption:'',platform:'Facebook + Instagram',status:'to_write',at:$('#ideaDate').value+'T12:00',photos:{}});try{localStorage.setItem('rwmSocialDrafts',JSON.stringify(next));posts=next;render();renderCalendar();toast('Planned posts added.')}catch{toast('Could not save. Browser storage may be full.')}};
renderCalendar=function(){ $('#monthLabel').textContent=month.toLocaleDateString(undefined,{month:'long',year:'numeric'});$('#month').replaceChildren();['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].forEach(x=>{const b=document.createElement('b');b.textContent=x;$('#month').append(b)});for(let i=0;i<month.getDay();i++)$('#month').append(document.createElement('div'));const count=new Date(month.getFullYear(),month.getMonth()+1,0).getDate();for(let day=1;day<=count;day++){const d=document.createElement('div');d.className='day';const b=document.createElement('b');b.textContent=day;d.append(b);const items=posts.filter(p=>{const a=new Date(p.at);return p.at&&a.getFullYear()===month.getFullYear()&&a.getMonth()===month.getMonth()&&a.getDate()===day});['solar','landscaping'].forEach(biz=>{const matching=items.filter(p=>(p.business||'landscaping')===biz);if(!matching.length)return;const name=document.createElement('strong');name.textContent=biz==='solar'?'Solar':'Landscaping';d.append(name);for(const [status,label] of [['to_write','To write'],['draft','Drafts'],['posted','Posted']]){const subset=matching.filter(p=>(p.status||'draft')===status);if(!subset.length)continue;const button=document.createElement('button');button.className='calendar-count';button.textContent=subset.length+' '+label;button.onclick=()=>{go('overview');toast('Matching items shown in your content queue.');};d.append(button)}});$('#month').append(d)}};
$('#accountList').replaceChildren();for(const [name,fb,ig] of [['RWM Landscaping','https://www.facebook.com/RWMlandscaping','https://www.instagram.com/rwmlandscaping/'],['RWM Solar (Facebook currently The Solar Brit)','https://www.facebook.com/profile.php?id=61583112135543','https://www.instagram.com/thesolarbritnj/']]){const d=document.createElement('div');d.className='post';const t=document.createElement('strong');t.textContent=name;d.append(t);for(const [label,url] of [['Facebook',fb],['Instagram',ig]]){const a=document.createElement('a');a.href=url;a.target='_blank';a.rel='noopener';a.textContent=label+' ↗ ';d.append(a)}const p=document.createElement('p');p.textContent='Identified for setup · not authorized or connected';d.append(p);$('#accountList').append(d)}
const info=document.createElement('p');info.className='notice';info.textContent='Connection requires the RWM SOCIAL Meta developer app, a secure authorization callback and your Facebook approval. No access tokens are stored in this browser.';$('#accountList').append(info);
render();
