(async()=>{
const vm=require('node:vm'),fs=require('node:fs'),assert=require('node:assert/strict');
class Element{constructor(){this.children=[];this.style={};this.value='';this.classList={toggle(){}}}append(...x){this.children.push(...x)}replaceChildren(){this.children=[]}before(){}setAttribute(){}dispatchEvent(){this.oninput?.()}get textContent(){return (this.text||'')+this.children.map(c=>c.textContent).join(' ')}set textContent(v){this.text=String(v)}reset(){}addEventListener(name,fn){this['on'+name]=fn}focus(){this.focused=true}}
const elements=new Map();const get=s=>{if(!elements.has(s))elements.set(s,new Element());return elements.get(s)};const data=new Map();const context=vm.createContext({document:{querySelector:get,querySelectorAll:()=>[],createElement:()=>new Element()},localStorage:{getItem:k=>data.get(k),setItem:(k,v)=>data.set(k,v)},crypto:require('node:crypto').webcrypto,Date,Event:class{},setTimeout:()=>{},confirm:()=>true});
context.window=context;vm.runInContext(fs.readFileSync(require('node:path').join(__dirname,'../content-tools.js'),'utf8'),context);
vm.runInContext(fs.readFileSync(require('node:path').join(__dirname,'../app.js'),'utf8'),context);
vm.runInContext(`posts=[{id:'s',title:'Solar idea',business:'solar',status:'to_write',caption:'',platform:'Facebook',at:'2026-10-09T12:00'},{id:'l',title:'Landscape draft',business:'landscaping',status:'draft',caption:'Done',consent:true,platform:'Facebook',at:'2026-10-09T12:00'}];month=new Date(2026,9,1);renderCalendar();`,context);
const oct9=get('#month').children.find(e=>e.children[0]?.textContent==='9');const button=oct9.children.find(e=>e.textContent==='1 To write');assert(button);button.onclick();assert.equal(get('#queue').children.length,1);assert(get('#queue').textContent.includes('Solar idea'));assert(!get('#queue').textContent.includes('Landscape draft'));
get('#clearQueueFilter').onclick();const draft=get('#queue').children.find(e=>e.textContent.includes('Landscape draft'));await draft.children.find(e=>e.textContent==='Approve draft').onclick();assert.equal(JSON.parse(data.get('rwmSocialDrafts')).find(p=>p.id==='l').status,'approved');
vm.runInContext(`posts=[{id:'x',title:'No consent',status:'draft',business:'solar',caption:'Ready',platform:'Facebook',consent:false}];render();`,context);await get('#queue').children[0].children.find(e=>e.textContent==='Approve draft').onclick();assert(get('#toast').textContent.includes('permission'));console.log('PASS: runtime initialization, calendar filtering, approval persistence and consent rejection');

vm.runInContext(`posts=[{id:'a',title:'Roof work',business:'solar',status:'approved',caption:'Reviewed',consent:true,platform:'Facebook',at:'2026-10-09T12:00',sourceJobId:42,photoPaths:{before:'saved/path'},photos:{before:'https://example.invalid/photo'}},{id:'b',title:'Garden',business:'landscaping',status:'draft',caption:'Fence',platform:'Facebook',at:''}];render();`,context);
get('#queueSearch').value='FENCE';get('#queueSearch').oninput();assert.equal(get('#queue').children.length,1);assert(get('#queue').textContent.includes('Garden'));
get('#queueSearch').value='';get('#queueSearch').oninput();get('#queueUndated').checked=true;get('#queueUndated').onchange();assert.equal(get('#queue').children.length,1);assert(get('#queue').textContent.includes('Garden'));get('#clearQueueFilter').onclick();
let approved=get('#queue').children.find(e=>e.textContent.includes('Roof work'));
approved.children.find(e=>e.textContent==='Duplicate as draft').onclick();assert.equal(vm.runInContext('editingId',context),null);assert.equal(vm.runInContext('editingSourceJobId',context),null);assert.equal(get('#permission').checked,undefined);assert.equal(get('#postTitle').value,'Roof work (copy)');
get('#removebefore').onclick();assert.equal(vm.runInContext('photoData.before',context),undefined);assert.equal(vm.runInContext('editingPhotoPaths.before',context),undefined);assert.equal(vm.runInContext('posts[0].photoPaths.before',context),'saved/path');
get('#cancelEdit').onclick();assert.equal(vm.runInContext('editingId',context),null);
const dateForm=approved.children.find(e=>e.children.some(c=>c.textContent==='Update date'));dateForm.children[0].value='2026-10-12T09:00';await dateForm.onsubmit({preventDefault(){}});const moved=JSON.parse(data.get('rwmSocialDrafts')).find(p=>p.id==='a');assert.equal(moved.status,'draft');assert.equal(moved.at,'2026-10-12T09:00');
get('#caption').value='hello';get('#caption').oninput();assert.equal(get('#captionCount').textContent,'5 / 5,000 characters');
get('#business').value='solar';get('#service').value='Solar';get('#postTitle').value='New installation';get('#suggest').onclick();assert(get('#caption').value.includes('#RWMSolar'));assert(!get('#caption').value.includes('Landscaping'));
get('#jumpMonth').value='2027-02';get('#jumpMonth').onchange();assert(get('#monthLabel').textContent.includes('2027'));
const feb1=get('#month').children.find(e=>e.children[0]?.textContent==='1');feb1.children.find(e=>e.textContent==='+ Plan content').onclick();assert.equal(get('#ideaDate').value,'2027-02-01');
const tools=context.SocialTools;const fixture=[{title:'Z',at:''},{title:'A',at:'2026-11-01T12:00'},{title:'B',at:'2026-10-01T12:00'}];assert.equal(tools.filterQueue(fixture,{business:'all',status:'all',date:''},'','planned')[0].title,'B');assert.equal(tools.filterQueue(fixture,{business:'all',status:'all',date:''},'','title')[0].title,'A');assert.equal(fixture[0].title,'Z');
console.log('PASS: search, sort, undated filter, copy isolation, date review reset, photo removal, cancel, counter, business captions and month planning');
})().catch(e=>{console.error(e);process.exit(1)});

