(async()=>{
const vm=require('node:vm'),fs=require('node:fs'),assert=require('node:assert/strict');
class Element{constructor(){this.children=[];this.style={};this.value='';this.classList={toggle(){}}}append(...x){this.children.push(...x)}replaceChildren(){this.children=[]}before(){}setAttribute(){}dispatchEvent(){this.oninput?.()}get textContent(){return (this.text||'')+this.children.map(c=>c.textContent).join(' ')}set textContent(v){this.text=String(v)}reset(){}}
const elements=new Map();const get=s=>{if(!elements.has(s))elements.set(s,new Element());return elements.get(s)};const data=new Map();const context=vm.createContext({document:{querySelector:get,querySelectorAll:()=>[],createElement:()=>new Element()},localStorage:{getItem:k=>data.get(k),setItem:(k,v)=>data.set(k,v)},crypto:require('node:crypto').webcrypto,Date,Event:class{},setTimeout:()=>{},confirm:()=>true});
vm.runInContext(fs.readFileSync(require('node:path').join(__dirname,'../app.js'),'utf8'),context);
vm.runInContext(`posts=[{id:'s',title:'Solar idea',business:'solar',status:'to_write',caption:'',platform:'Facebook',at:'2026-10-09T12:00'},{id:'l',title:'Landscape draft',business:'landscaping',status:'draft',caption:'Done',consent:true,platform:'Facebook',at:'2026-10-09T12:00'}];month=new Date(2026,9,1);renderCalendar();`,context);
const oct9=get('#month').children.find(e=>e.children[0]?.textContent==='9');const button=oct9.children.find(e=>e.textContent==='1 To write');assert(button);button.onclick();assert.equal(get('#queue').children.length,1);assert(get('#queue').textContent.includes('Solar idea'));assert(!get('#queue').textContent.includes('Landscape draft'));
get('#clearQueueFilter').onclick();const draft=get('#queue').children.find(e=>e.textContent.includes('Landscape draft'));await draft.children.find(e=>e.textContent==='Approve draft').onclick();assert.equal(JSON.parse(data.get('rwmSocialDrafts')).find(p=>p.id==='l').status,'approved');
vm.runInContext(`posts=[{id:'x',title:'No consent',status:'draft',business:'solar',caption:'Ready',platform:'Facebook',consent:false}];render();`,context);await get('#queue').children[0].children.find(e=>e.textContent==='Approve draft').onclick();assert(get('#toast').textContent.includes('permission'));console.log('PASS: runtime initialization, calendar filtering, approval persistence and consent rejection');

})().catch(e=>{console.error(e);process.exit(1)});
