(async()=>{
const vm=require('node:vm'),fs=require('node:fs'),assert=require('node:assert/strict');
class Element{constructor(){this.children=[];this.style={};this.value='';this.classList={toggle(){},add(){}}}append(...x){this.children.push(...x)}replaceChildren(){this.children=[]}before(){}setAttribute(){}dispatchEvent(event){this['on'+(event.type||'input')]?.(event);for(const fn of this.listeners?.[event.type||'input']||[])fn(event)}get textContent(){return (this.text||'')+this.children.map(c=>c.textContent).join(' ')}set textContent(v){this.text=String(v)}reset(){}addEventListener(name,fn){this.listeners||={};(this.listeners[name]||=[]).push(fn)}click(){this.onclick?.()}reportValidity(){return true}focus(){this.focused=true}}
const elements=new Map();const get=s=>{if(!elements.has(s))elements.set(s,new Element());return elements.get(s)};const data=new Map();let allowDiscard=true,copied='',exported,readerList=[];class Reader{constructor(){readerList.push(this)}readAsDataURL(){}}const windowEvents={};const context=vm.createContext({document:{querySelector:get,querySelectorAll:()=>[],createElement:()=>new Element()},localStorage:{getItem:k=>data.get(k),setItem:(k,v)=>data.set(k,v)},crypto:require('node:crypto').webcrypto,Date,Event:class{constructor(type){this.type=type}},setTimeout:()=>{},confirm:()=>allowDiscard,addEventListener:(name,fn)=>windowEvents[name]=fn,FileReader:Reader,Blob,URL:{createObjectURL:b=>{exported=b;return 'blob:test'},revokeObjectURL(){}},navigator:{clipboard:{writeText:async text=>{copied=text}}}});
context.window=context;vm.runInContext(fs.readFileSync(require('node:path').join(__dirname,'../content-tools.js'),'utf8'),context);
vm.runInContext(fs.readFileSync(require('node:path').join(__dirname,'../app.js'),'utf8'),context);
vm.runInContext(`posts=[{id:'s',title:'Solar idea',business:'solar',status:'to_write',caption:'',platform:'Facebook',at:'2026-10-09T12:00'},{id:'l',title:'Landscape draft',business:'landscaping',status:'draft',caption:'Done',consent:true,platform:'Facebook',at:'2026-10-09T12:00'}];month=new Date(2026,9,1);renderCalendar();`,context);
const oct9=get('#month').children.find(e=>e.children[0]?.textContent==='9');const button=oct9.children.find(e=>e.textContent==='1 To write');assert(button);button.onclick();assert.equal(get('#queue').children.length,1);assert(get('#queue').textContent.includes('Solar idea'));assert(!get('#queue').textContent.includes('Landscape draft'));
get('#clearQueueFilter').onclick();const draft=get('#queue').children.find(e=>e.textContent.includes('Landscape draft'));await draft.children.find(e=>e.textContent==='Approve draft').onclick();assert.equal(JSON.parse(data.get('rwmSocialDrafts')).find(p=>p.id==='l').status,'approved');
vm.runInContext(`posts=[{id:'x',title:'No consent',status:'draft',business:'solar',caption:'Ready',platform:'Facebook',consent:false}];render();`,context);await get('#queue').children[0].children.find(e=>e.textContent==='Approve draft').onclick();assert(get('#toast').textContent.includes('permission'));console.log('PASS: runtime initialization, calendar filtering, approval persistence and consent rejection');

vm.runInContext(`posts=[{id:'a',title:'Roof work',business:'solar',status:'approved',caption:'Reviewed',consent:true,platform:'Facebook',at:'2026-10-09T12:00',sourceJobId:42,photoPaths:{before:'saved/path'},photos:{before:'https://example.invalid/photo'}},{id:'b',title:'Garden',business:'landscaping',status:'draft',caption:'Fence',platform:'Facebook',at:''}];render();`,context);
get('#queueSearch').value='FENCE';get('#queueSearch').oninput();assert.equal(get('#queue').children.length,1);assert(get('#queue').textContent.includes('Garden'));
get('#queueSearch').value='';get('#queueSearch').oninput();get('#queueUndated').checked=true;get('#queueUndated').onchange();assert.equal(get('#queue').children.length,1);assert(get('#queue').textContent.includes('Garden'));get('#clearQueueFilter').onclick();
let approved=get('#queue').children.find(e=>e.textContent.includes('Roof work'));
approved.children.find(e=>e.textContent==='Duplicate as draft').onclick();assert.equal(vm.runInContext('editingId',context),null);assert.equal(vm.runInContext('editingSourceJobId',context),null);assert.equal(get('#permission').checked,undefined);assert.equal(get('#postTitle').value,'Roof work (copy)');
get('#removebefore').onclick();assert.equal(vm.runInContext('photoData.before',context),undefined);assert.equal(vm.runInContext('editingPhotoPaths.before',context),undefined);assert.equal(vm.runInContext('posts[0].photoPaths.before',context),'saved/path');
get('#cancelEdit').onclick();assert.equal(vm.runInContext('editingId',context),null);
const dateForm=approved.children.find(e=>e.children.some(c=>c.textContent==='Update date'));dateForm.children[0].value='2026-10-12T09:00';await dateForm.onsubmit({preventDefault(){}});const moved=JSON.parse(data.get('rwmSocialDrafts')).find(p=>p.id==='a');assert.equal(moved.status,'draft');assert.equal(moved.at,'2026-10-12T09:00');
get('#caption').value='hello';get('#caption').dispatchEvent({type:'input'});assert.equal(get('#captionCount').textContent,'5 / 5,000 characters');
get('#business').value='solar';get('#service').value='Solar';get('#postTitle').value='New installation';get('#suggest').onclick();assert(get('#caption').value.includes('#RWMSolar'));assert(!get('#caption').value.includes('Landscaping'));
get('#jumpMonth').value='2027-02';get('#jumpMonth').onchange();assert(get('#monthLabel').textContent.includes('2027'));
const feb1=get('#month').children.find(e=>e.children[0]?.textContent==='1');feb1.children.find(e=>e.textContent==='+ Plan content').onclick();assert.equal(get('#ideaDate').value,'2027-02-01');
const tools=context.SocialTools;const fixture=[{title:'Z',at:''},{title:'A',at:'2026-11-01T12:00'},{title:'B',at:'2026-10-01T12:00'}];assert.equal(tools.filterQueue(fixture,{business:'all',status:'all',date:''},'','planned')[0].title,'B');assert.equal(tools.filterQueue(fixture,{business:'all',status:'all',date:''},'','title')[0].title,'A');assert.equal(fixture[0].title,'Z');
console.log('PASS: search, sort, undated filter, copy isolation, date review reset, photo removal, cancel, counter, business captions and month planning');
// Private queue tooling: exports contain no media paths, and formula-like cells stay text.
const csv=tools.csv([{title:'=IMPORTXML(1)',caption:'  +cmd',business:'solar',platform:'Instagram',photoPaths:{before:'private/path'}}]);assert(csv.includes("'=IMPORTXML"));assert(csv.includes("'  +cmd"));assert(!csv.includes('private/path'));
const missing=tools.readiness({platform:'Instagram',caption:'x'.repeat(2201),consent:false});assert(missing.includes('Confirm marketing permission'));assert(missing.includes('Add an Instagram photo'));assert(missing.some(x=>x.includes('2,200')));
assert(!tools.readiness({platform:'Instagram',caption:'Ready',consent:true,photoPaths:{before:'saved'},at:'2099-01-01T12:00'}).length);
const overdue=[{title:'Old solar',business:'solar',status:'draft',at:'2000-01-01T12:00'},{title:'Already posted',business:'solar',status:'posted',at:'2000-01-01T12:00'},{title:'Undated',business:'landscaping',status:'draft'}];assert.equal(tools.filterQueue(overdue,{business:'all',status:'all',date:''},'','newest',false,true).length,1);assert.equal(tools.summary(overdue,'solar').overdue,1);
vm.runInContext(`posts=[{id:'ig',title:'Long IG',caption:'x'.repeat(2201),business:'solar',platform:'Instagram',consent:true,photos:{before:'x'},status:'draft'}];render();`,context);await get('#queue').children[0].children.find(e=>e.textContent==='Approve draft').onclick();assert(get('#toast').textContent.includes('2,200'));
await get('#queue').children[0].children.find(e=>e.textContent==='Copy caption').onclick();assert.equal(copied.length,2201);get('#exportQueue').onclick();assert((await exported.text()).includes('Long IG'));assert(get('#businessSummary').textContent.includes('RWM Solar'));
// Discard rejection preserves the existing composer and source association.
vm.runInContext(`composerDirty=true;editingId='keep';`,context);allowDiscard=false;get('#newPost').onclick();assert.equal(vm.runInContext('editingId',context),'keep');get('#cancelEdit').onclick();assert.equal(vm.runInContext('editingId',context),'keep');allowDiscard=true;get('#newPost').onclick();assert.equal(vm.runInContext('editingId',context),null);
get('#before').files=[{type:'image/jpeg',size:20}];get('#before').onchange();const stale=readerList.at(-1);get('#newPost').onclick();stale.result='stale';stale.onload();assert.equal(vm.runInContext('photoData.before',context),undefined);
get('#before').onchange();const first=readerList.at(-1);get('#before').onchange();const second=readerList.at(-1);first.result='old';first.onload();assert.equal(vm.runInContext('photoData.before',context),undefined);second.result='latest';second.onload();assert.equal(vm.runInContext('photoData.before',context),'latest');
get('#after').files=[{type:'image/png',size:30}];get('#after').onchange();await get('#postForm').onsubmit({preventDefault(){}});assert(get('#toast').textContent.includes('finish loading'));readerList.at(-1).onerror();assert.equal(vm.runInContext('photoReading.after',context),false);assert(get('#toast').textContent.includes('could not be read'));
let blocked=false;windowEvents.beforeunload({preventDefault(){blocked=true}});assert(blocked);
// Job results paginate, search locally, and reuse the correct business's existing post.
const page=Array.from({length:51},(_,i)=>({id:i+1,customer_name:'Customer '+(i+1),service:'Mowing',scheduled_date:'2026-10-09'}));const offsets=[];context.SocialCloud={jobs:async offset=>{offsets.push(offset);return offset===0?page:[{id:51,customer_name:'Customer 51',service:'Mowing',scheduled_date:'2026-10-09'}]}};
vm.runInContext(`cloudMode=true;composerDirty=false;posts=[{id:'existing',sourceJobId:1,business:'solar',title:'Existing solar',platform:'Facebook',caption:'Done',status:'draft'}];`,context);get('#jobBusiness').value='solar';await get('#loadOpsJobs').onclick();assert.equal(get('#opsJobList').children.length,50);assert.equal(get('#moreOpsJobs').hidden,false);assert(get('#opsJobList').textContent.includes('Open existing post'));
get('#hideQueuedJobs').checked=true;get('#hideQueuedJobs').onchange();assert.equal(get('#opsJobList').children.length,49);get('#hideQueuedJobs').checked=false;get('#jobSearch').value='Customer 1';get('#jobSearch').oninput();assert(get('#opsJobList').children.length<50);const existing=get('#opsJobList').children.find(e=>e.textContent.includes('Open existing post'));existing.children.find(e=>e.textContent==='Open existing post').onclick();assert.equal(vm.runInContext('editingId',context),'existing');
get('#jobSearch').value='';await get('#moreOpsJobs').onclick();assert.equal(get('#opsJobList').children.length,51);assert.equal(get('#moreOpsJobs').hidden,true);assert.deepEqual(offsets,[0,50]);get('#jobBusiness').value='landscaping';get('#jobBusiness').onchange();assert(!get('#opsJobList').textContent.includes('Open existing post'));
console.log('PASS: readiness, private CSV export, business totals, overdue filter, clipboard, discard guards, stale photo reads and paginated job review');
// Paged queues only select visible items, and filtered-out selections cannot be mutated.
vm.runInContext(`cloudMode=false;composerDirty=false;posts=Array.from({length:25},(_,i)=>({id:'page-'+i,title:'Item '+i,business:i%2?'solar':'landscaping',status:i===0?'approved':'draft',platform:'Facebook',caption:'Ready',consent:true,at:'2027-03-01T12:00'}));setQueueFilter({business:'all',status:'all',date:''});`,context);
assert.equal(get('#queue').children.length,20);assert(get('#queuePage').textContent.includes('of 2'));get('#selectPage').onclick();assert.equal(vm.runInContext('selectedPosts.size',context),20);get('#queueNext').onclick();assert.equal(get('#queue').children.length,5);get('#selectPage').onclick();assert.equal(vm.runInContext('selectedPosts.size',context),25);get('#clearSelection').onclick();assert.equal(vm.runInContext('selectedPosts.size',context),0);
get('#queuePrevious').onclick();get('#selectPage').onclick();get('#bulkDate').value='2027-03-03T09:30';await get('#bulkDateForm').onsubmit({preventDefault(){}});assert.equal(vm.runInContext('posts[0].status',context),'draft');assert.equal(vm.runInContext('posts[0].at',context),'2027-03-03T09:30');assert.equal(vm.runInContext('posts[24].at',context),'2027-03-01T12:00');assert.equal(vm.runInContext('posts[1].business',context),'solar');
get('#selectPage').onclick();await get('#bulkClearDate').onclick();assert.equal(vm.runInContext('posts[0].at',context),'');assert.equal(vm.runInContext('posts[24].at',context),'2027-03-01T12:00');
vm.runInContext(`posts[0]={...posts[0],status:'approved'};render();`,context);get('#selectPage').onclick();await get('#bulkReturnDraft').onclick();assert.equal(vm.runInContext('posts[0].status',context),'draft');get('#selectPage').onclick();get('#queueBusiness').value='solar';get('#queueStatus').value='all';get('#queueDate').value='';get('#queueBusiness').onchange();assert.equal(vm.runInContext('selectedPosts.size',context),0);
// Calendar totals and weekly agenda count one item, including dual-platform posts.
vm.runInContext(`posts=[{id:'solar',business:'solar',title:'Solar week',caption:'Ready',platform:'Facebook + Instagram',status:'draft',at:'2027-03-03T09:00'},{id:'garden',business:'landscaping',title:'Garden week',caption:'Ready',platform:'Facebook',status:'approved',at:'2027-03-03T10:00'}];month=new Date(2027,2,1);agendaDay='2027-03-03';renderCalendar();`,context);assert(get('#monthTotals').textContent.includes('1 Draft'));assert(get('#monthTotals').textContent.includes('1 Approved'));assert(get('#weekAgenda').textContent.includes('Solar week'));assert(get('#weekAgenda').textContent.includes('Garden week'));get('#calendarBusiness').value='solar';get('#calendarBusiness').onchange();assert(get('#monthTotals').textContent.includes('0 Approved'));assert(!get('#weekAgenda').textContent.includes('Garden week'));get('#nextWeek').onclick();assert(!get('#weekAgenda').textContent.includes('Solar week'));get('#previousWeek').onclick();assert(get('#weekAgenda').textContent.includes('Solar week'));
// Strict backups drop media/source/approval/consent and refuse other company IDs.
const id1='11111111-1111-4111-8111-111111111111',id2='22222222-2222-4222-8222-222222222222';const originals=[{id:id1,business:'solar',title:'Solar backup',caption:'Ready',service:'Solar',status:'approved',platform:'Facebook + Instagram',at:'2027-03-03T09:00',photos:{before:'data:image/jpeg;base64,private'},photoPaths:{before:'secret/path'},consent:true,sourceJobId:123},{id:id2,business:'landscaping',title:'Garden idea',caption:'',service:'Landscaping',status:'to_write',platform:'Facebook',at:''}];const backup=tools.backup(originals,'company-A');assert(!JSON.stringify(backup).includes('secret/path'));assert(!JSON.stringify(backup).includes('data:image'));assert.throws(()=>tools.restore(backup,'company-B'),/different company/);const restored=tools.restore(backup,'company-A');assert.equal(restored[0].status,'draft');assert.equal(restored[0].consent,false);assert.equal(restored[0].sourceJobId,null);assert.equal(Object.keys(restored[0].photoPaths).length,0);assert.equal(restored[1].business,'landscaping');assert.equal(restored[1].status,'to_write');assert.throws(()=>tools.restore({...backup,posts:[backup.posts[0],backup.posts[0]]},'company-A'),/duplicate/);assert.throws(()=>tools.restore({...backup,posts:[{...backup.posts[0],at:'2027-02-30T09:00'}]},'company-A'),/invalid text or dates/);assert.throws(()=>tools.restore({...backup,posts:[{...backup.posts[0],business:'other'}]},'company-A'),/unsupported/);
assert.equal(tools.dayString(tools.weekStart('2027-01-01')),'2026-12-27');assert.throws(()=>tools.bulk(originals,new Set([id1]),'move','bad'),/valid planned/);const published={...originals[0],status:'posted'};assert.equal(tools.bulk([published],new Set([id1]),'clear')[0],published);
vm.runInContext(`posts=[];cloudMode=false;setQueueFilter({business:'all',status:'all',date:''});`,context);const localBackup={...backup,companyId:null};get('#restorePlan').files=[{size:100,text:async()=>JSON.stringify(localBackup)}];await get('#restorePlan').onchange();assert.equal(vm.runInContext('posts.length',context),2);assert.equal(vm.runInContext('posts[0].business',context),'solar');await get('#restorePlan').onchange();assert.equal(vm.runInContext('posts.length',context),2);assert(get('#toast').textContent.includes('already exist'));get('#backupPlan').onclick();assert.equal(JSON.parse(await exported.text()).format,'rwm-social-text-plan');
console.log('PASS: queue pages, filter-safe selections, bulk dates/review, calendar totals, weekly agenda and validated repeat-safe text-plan restore');
})().catch(e=>{console.error(e);process.exit(1)});

